login = 'https://studentportalbeta.unilag.edu.ng/users/login'
accomodationHalls = 'https://studentportalbeta.unilag.edu.ng/accomodation/accomodationHalls'
accomodationChecks = 'https://studentportalbeta.unilag.edu.ng/accomodation/accommodationChecks'
accomodationReservation = 'https://studentportalbeta.unilag.edu.ng/accomodation/saveAccommodationReservation'
accomodationConfirmation = 'https://studentportalbeta.unilag.edu.ng/accomodation/accomodationConfirmation'